psql example -c "INSERT INTO Dogs(id,raza_dog)VALUES('1','Affenpinscher')"
psql example -c "INSERT INTO Razas_dogs(id, descripcion, consejos, personalidad,  origen, salud, ejercicio, nutricion, aseo, raza_nino)
 VALUES ('1',
 'Pese a su apariencia de terrier y su traviesa expresión similar a la de un mono, el Affenpinscher es un perro de compañía que en edad adulta mide entre 24 y 28 cm de la altura (contando desde las patas hasta la parte superior de la escápula) y pesa unos 3 o 4 kg. Su pelaje es áspero y suele ser negro aunque, a veces, también presenta un leve tono gris.',
 'Perro apto para dueños sin experiencia. Se requiere un adiestramiento básico. Le gustan los paseos activos. Le gusta pasear media hora al día. Perro pequeño. Babeo mínimo. Requiere aseo una vez por semana. Raza hipoalergénica. Perro expresivo y ladrador. No es un perro guardián. Puede necesitar entrenamiento para vivir con otras mascotas. Puede necesitar entrenamiento para vivir con niños',
 'El affen es alegre y seguro de sí mismo, irascible, tenaz y valiente, aunque muy cariñoso con sus dueños. Suele mostrarse receloso con los desconocidos; por lo que es esencial que se le socialice ya desde cachorro.',
 'El Affenpinscher, travieso y gracioso, es una de las razas más antiguas cuyo origen se remonta al siglo XVII. En Alemania, su lugar de origen, la palabra «affen» significa burlarse y «pinscher» equivale a terrier. El affen es el antepasado de otras dos razas, el grifón belga y el grifón de Bruselas, que también tienen una cara similar a la de un mono. Aunque los affen tienen las agallas de los terrier, son demasiado pequeños para ser perros de trabajo y se adquieren sobre todo como animales de compañía.',
 'La raza affenpinscher es una raza sana por lo general. Sin embargo, como ocurre con muchas razas pequeñas, puede padecer desplazamientos temporales de la rótula (luxaciones de rótula), problemas de cadera y de tráquea.',
 'A pesar de su tamaño reducido, es un perro activo y requiere de una cantidad razonable de ejercicio (de 20 a 40 minutos al día). Le gustan los juegos que le ayuden a ejercitar la mente, además del cuerpo, pero no son demasiado bulliciosos.', 
 'Los perros de tamaño miniatura tienen un metabolismo rápido, lo que significa que queman energía a un ritmo muy alto. Esto supone que, con un estómago tan pequeño, deben comer poco pero a menudo. Los alimentos para razas pequeñas están específicamente ideados con proporciones adecuadas de nutrientes clave y unos granos de pienso de menor tamaño que se adapten a bocas más pequeñas. Esto, además, estimula la masticación y mejora la digestión.',
 'El pelaje áspero y duro es lanudo en algunas partes y su aspecto natural es despeinado, por lo que no requiere grandes cuidados: un cepillado a la semana bastará.',
 'Aunque tradicionalmente la mayoría de perros son buenos con los niños, todos los perros y niños necesitan que se les enseñe a llevarse bien y a respetarse mutuamente para estar seguros. Aun así, los perros y los niños pequeños nunca deberían quedarse solos y los adultos deben supervisar todas las interacciones entre ellos.'
 );"
psql example -c "INSERT INTO Dogs(id,raza_dog)VALUES('2','Afgano')"
psql example -c "INSERT INTO Razas_dogs(id,descripcion, consejos, personalidad, origen, salud, ejercicio, nutricion, aseo, raza_nino) 
VALUES ('2',
'El Afgano es un perro de aspecto noble que luce con orgullo y elegancia su largo y brillante pelaje, que es su mayor atractivo. Es una raza grande con una altura de 68 a 74 cm en la edad adulta para el macho y de 63 a 69 cm en el caso de las hembras. Su magnífico pelaje puede ser de cualquier color, desde negro a plateado, pasando por todos los colores y combinaciones posibles. El peso medio es de 25 kg aproximadamente con un mínimo de unos 20 kg y un máximo de unos 27 kg dependiendo del sexo y la constitución del perro.',
'Perro apto para dueños con algo de experiencia. Se requiere un adiestramiento extra. Le gustan los paseos activos. Le gusta pasear más de dos horas al día. Perro grande. Babeo mínimo. Requiere aseo diario. Raza no hipoalergénica. Perro expresivo y ladrador. No es un perro guardián. Puede necesitar entrenamiento para vivir con otras mascotas. Puede necesitar entrenamiento para vivir con niños.',
'A menudo se muestra distante con los desconocidos, por lo que es imprescindible la socialización para este regio perro, al igual que un adiestramiento para cachorros, sobre todo para que aprenda a responder a la llamada del dueño. No mostrará ninguna reserva con su familia y las personas a las que conoce. Es extraordinariamente leal y cariñoso. El afgano está hecho para correr y su momento más feliz es cuando corre a toda velocidad con el viento acariciándole el pelaje detrás de una pelota o una ardilla a la que ha descubierto.',
'El Afgano, que es una de las razas más antiguas del mundo, atrajo por primera vez la atención de Occidente en el siglo XIX. Sus orígenes exactos se desconocen, aunque abundan las leyendas. En Afganistán cohabitan diferentes variaciones de la raza y se utilizan para guardar y guiar rebaños y ganado, así como para ayudar en la caza en la montaña de ciervos, antílopes, liebres e incluso depredadores como los lobos, los chacales y los leopardos de las nieves.',
'El afgano es una raza sana y robusta en general con pocos problemas específicos que sean frecuentes',
'Un afgano adulto necesita mucho ejercicio (preferentemente, unas dos horas al día o más). Le encanta correr libre, pero, debido a su tendencia a perseguir y cazar, primero asegúrate de que responderá a tu llamada y suéltalo solo en áreas seguras, lejos de peligros como el tráfico',
'Los perros de razas grandes requieren un equilibrio de nutrientes diferente, incluyendo los minerales y las vitaminas, al de los perros de menor tamaño. El afgano es propenso a sufrir distensión del estómago y otros problemas estomacales; unas comidas más reducidas y frecuentes podrían minimizar el riesgo.',
'El glamuroso pelaje, largo y sedoso, tiene un precio: resulta muy laborioso mantenerlo en perfectas condiciones. Recomendamos cepillarlo a diario para evitar enredos y nudos, y necesitará baños regulares para mantenerlo limpio. Es especialmente importante cepillarlo bien cuando pierde el pelaje de cachorro para evitar que el pelo nuevo se enrede con el antiguo, lo que le causaría molestias.',
'Aunque tradicionalmente la mayoría de perros son buenos con los niños, todos los perros y niños necesitan que se les enseñe a llevarse bien y a respetarse mutuamente para estar seguros. Aun así, los perros y los niños pequeños nunca deberían quedarse solos y los adultos deben supervisar todas las interacciones entre ellos.',
);"
psql example -c "INSERT INTO Dogs(id,raza_dog)VALUES('3','Akita japonés')"
psql example -c "INSERT INTO Razas_dogs(id,descripcion, consejos, personalidad, origen, salud, ejercicio, nutricion, aseo, raza_nino) 
VALUES ('3',
'El Akita es un perro grande y fuerte de gran esencia y dignidad. El porte orgulloso de su cabeza se ve realzado por unas orejas pequeñas y unos ojos oscuros. Son impresionantes gracias a su pelaje grueso y afelpado, de color rojo leonado, sésamo, atigrado y blanco. Los machos adultos miden entre 64 y 70 cm y las hembras, entre 58 y 64 cm. El peso puede estar entre 34 y 50 kg.',
'Perro apto para dueños con experiencia. Se requiere un adiestramiento extra. Le gustan los paseos activos. Le gusta pasear una o dos horas al día. Perro grande. Babeo intenso. Requiere aseo diario. Raza no hipoalergénica. Perro tranquilo. Perro guardián. Ladra, está alerta y tiene aspecto protector. Puede necesitar entrenamiento para vivir con otras mascotas. Puede necesitar entrenamiento para vivir con niños',
'Son perros fuertes, tanto físicamente como de carácter, y no se recomiendan para dueños primerizos. Hace falta experiencia en el manejo, adiestramiento y socialización, tanto inicial como continua. No obstante, son muy fieles a su familia. Son valientes y buenos guardianes y no ladran demasiado. No hay que olvidar que tiene un fuerte instinto de caza.', 
'El akita, que se crio originalmente en la provincia de Akita en el siglo XVII, es la raza japonesa de mayor tamaño. Algunas teorías afirman que estos perros se criaron originalmente para la caza del jabalí, el ciervo y el oso negro; sin embargo, otras sostienen que el objetivo eran las peleas de perros. Aun así, cuando las peleas de perros perdieron popularidad en Japón (y en Europa), estos perros se emplearon para la caza. A finales del siglo XIX, se importaron otras razas y las razas japonesas quedaron relegadas a un segundo y tercer plano. Se creó entonces la Sociedad para la Conservación de los Perros Japoneses con el fin de conservar las razas autóctonas, que se declararon patrimonio nacional.',
'Al igual que muchas otras razas, el akita puede sufrir displasia de cadera (una enfermedad que puede provocar problemas de movilidad). Por tanto, es importante un examen de la cadera y de los ojos antes de dedicar al perro a la crianza.', 
'El akita necesita mucho ejercicio para que la musculatura se mantenga en buen estado. Dicho esto, si algún día te saltas el paseo un día, lo aceptará sin rechistar. Antes de dejarlo correr suelto, recuerda que es un perro de caza y que debes extremar las precauciones.',
'Los perros de razas grandes, además de tener un gran apetito, requieren un equilibrio de nutrientes diferente, incluyendo los minerales y las vitaminas, al de los perros de menor tamaño. El akita es propenso a sufrir distensión del estómago y otros problemas estomacales; unas comidas más reducidas y frecuentes podrían minimizar el riesgo',
'Hay que cepillar bien el pelaje dos o tres veces por semana para mantenerlo en óptimas condiciones. Dos veces al año, durante las grandes mudas, debes utilizar un peine metálico de doble dentado.',
'Aunque tradicionalmente la mayoría de perros son buenos con los niños, todos los perros y niños necesitan que se les enseñe a llevarse bien y a respetarse mutuamente para estar seguros. Aun así, los perros y los niños pequeños nunca deberían quedarse solos y los adultos deben supervisar todas las interacciones entre ellos.'
);"
psql example -c "INSERT INTO Dogs(id,raza_dog)VALUES('4','Basenji')"
psql example -c "INSERT INTO Razas_dogs(id,descripcion, consejos, personalidad, origen, salud, ejercicio, nutricion, aseo, raza_nino) 
VALUES ('4',
'Este perro de tamaño pequeño-mediano tiene una cola muy curvada y la frente arrugada. El pelaje es brillante, corto y suave y puede ser rojo y blanco, negro y blanco, negro, canela y blanco, tricolor o con muchos colores mezclados. La altura ideal para un adulto macho es de 43 cm (desde las patas hasta el punto más alto del omóplato) y de 40 cm para las hembras. En la edad adulta, el peso ideal para los machos es de 11 kg y para las hembras, 9,5 kg.',
'Perro apto para dueños con algo de experiencia. Se requiere algo de adiestramiento. Le gustan los paseos activos. Le gusta pasear una hora al día. Perro mediano. Babeo mínimo. Requiere aseo una vez por semana. Raza no hipoalergénica. Perro tranquilo. No es un perro guardián. Puede necesitar entrenamiento para vivir con otras mascotas.Puede necesitar entrenamiento para vivir con niños.',
'Estos perros son únicos porque no ladran, pero sí emiten unos aullidos similares al canto tirolés cuando se ponen nerviosos. Esta raza, despierta, independiente, autosuficiente y prácticamente inodora; es muy similar a un gato y hasta se ha visto a estos perros escalar árboles y vallas como los felinos. Es cariñoso con sus seres queridos, pero tiende a mostrarse distante con los desconocidos. Los basenjis suelen enfrentarse a otros perros, por lo que es indispensable la socialización a una edad temprana.',
'Los Basenji se crearon probablemente para ser perros de compañía para los faraones y hay retratos de ejemplares Basenji en las pirámides egipcias. Con el tiempo, la raza se trasladó al centro de África, donde se usó para matar a las ratas de largos dientes de la región del Congo. Estas ratas grandes y feroces eran una amenaza real para el ganado de los nativos, con lo que un buen perro de caza era esencial para la supervivencia. Occidente no conoció esta raza hasta la época victoriana, cuando los primeros exploradores africanos se fijaron en un «perro que no ladraba»',
'Las enfermedades heredadas más conocidas en los basenjis son un tipo de enfermedad renal (síndrome de Fanconi) y una clase de anemia. Hay pruebas genéticas para ambas dolencias. Al igual que en muchas otras razas, pueden aparecer trastornos oculares. Por lo tanto, es importante realizar un examen ocular y genético antes de dedicar al perro a la crianza.', 
'Criado para cazar en terrenos difíciles, el basenji necesita, como mínimo, una hora diaria de ejercicio y puede resistir más si se lo puedes ofrecer. Aunque no es fácil de adiestrar, es aconsejable hacer participar al basenji en algún tipo de deporte canino para mantener el cuerpo y la mente sanos. Desconocen lo que es una carretera y les cuesta orientarse en ella, por lo que hay que tomar precauciones cuando se ejercite cerca del tráfico.',
'Los perros pequeños tienen un metabolismo rápido, lo que significa que queman energía a un ritmo muy alto. Con un estómago tan pequeño, esto implica que deben comer poco pero a menudo. Los alimentos para razas pequeñas están específicamente ideados con proporciones adecuadas de nutrientes clave y unos granos de pienso de menor tamaño que se adapten a bocas más pequeñas. Esto, además, estimula la masticación y mejora la digestión.',
'El basenji se ocupa de la mayor parte de su aseo y su mantenimiento. El pelaje es corto, elegante y fino, y se puede limpiar con un guante una vez por semana para eliminar el pelo suelto. Las orejas y las uñas se pueden revisar periódicamente. Aparte de eso, poco más hace falta hacerle.',
'Aunque tradicionalmente la mayoría de perros son buenos con los niños, todos los perros y niños necesitan que se les enseñe a llevarse bien y a respetarse mutuamente para estar seguros. Aun así, los perros y los niños pequeños nunca deberían quedarse solos y los adultos deben supervisar todas las interacciones entre ellos'
);"
psql example -c "INSERT INTO Dogs(id,raza_dog)VALUES('5','Basset Azul de Gascuña')"
psql example -c "INSERT INTO Razas_dogs(id,descripcion, consejos, personalidad, origen, salud, ejercicio, nutricion, aseo, raza_nino)
 VALUES ('5',
 'El Basset Azul es un sabueso de aspecto noble que tiene el cuerpo largo y las patas cortas (típicas de la raza Basset). Es fuerte y atlético, pero no es un perro pesado ni voluminoso. De tamaño medio, mide entre 30 y 38 cm de altura en edad adulta y pesa entre 7 y 9 kilos. La característica más llamativa es el color de su pelaje: negro sobre un fondo blanco, cubierto de motas negras que le dan ese aspecto azulado, aunque a veces también pueden tener un tono canela. Para más información, consulta el estándar de la raza.',
 'Perro apto para dueños con algo de experiencia. Se requiere un adiestramiento extra. Le gustan los paseos activos. Le gusta pasear una o dos horas al día. Perro mediano. Babeo mínimo.Requiere aseo una vez por semana. Raza no hipoalergénica. Perro expresivo y ladrador. No es un perro guardián. Puede necesitar entrenamiento para vivir con otras mascotas. Perro familiar.',
 'El basset azul de Gascuña es cariñoso con su familia y amigos, pero un poco reservado con los demás. Es «sagaz» y «audaz», palabras que no suelen usarse para definir el estándar de una raza, lo cual sugiere que este perro es único en su especie. Como todos los perros, el basset azul es más feliz que nunca con el hocico pegado al suelo siguiendo el rastro de un olor interesante.',
 'Francia es el hogar original de muchos perros y, como indica su nombre, también incluye al Basset azul de Gascuña, un perro que proviene de Gascogne, al suroeste de Francia. Ya en el siglo XII se hablaba de los perros azules de esta región y se decía que ayudaban a cazar jabalíes y lobos, además de ciervos. La raza casi estuvo a punto de extinguirse a principios del siglo XX, pero el azul de Gascuña de patas más largas se usó en programas de crianza para salvar al Basset azul de la extinción.',
 'El basset azul no es conocido por sufrir muchos problemas de tipo hereditario. Al igual que otros perros con esta forma corporal, pueden ser más propensos a tener problemas de la columna y al desarrollo anómalo de las articulaciones.',
 'Como les pasa a la mayoría de los perros, puede quedarse sordo de tanto seguir a su hocico, por lo que es esencial adiestrarlo para que acuda cuando lo llamen, igual que enseñarlo a ir suelto solo por zonas seguras y sin tráfico. Como lo criaron para las cazas lentas y prolongadas, es más parecido a un corredor de fondo que a un velocista en distancias cortas, y necesita un par de horas al día de ejercicio para quemar toda su energía, además de la posibilidad de entrenar su olfato.',
 'La dieta de tu perro debe contener la proporción adecuada de todos los principales grupos de nutrientes. Además, deberá tener siempre agua fresca a su disposición. Es importante realizar comprobaciones regulares para mantener al perro en perfecta forma y recuerda darle de comer dos veces al día siguiendo las pautas de alimentación de su alimento específico. El basset azul es propenso a sufrir distensión del estómago y otros problemas estomacales; unas comidas más reducidas y frecuentes podrían minimizar el riesgo.',
 'Su pelaje corto y denso requiere poco mantenimiento. Solo necesitará un cepillado semanal para quitarle el pelo muerto y mantenerlo saludable. También se le puede dar un baño de vez en cuando si hace falta. Sus oídos requieren una atención especial, ya que puede tener infecciones del oído debido al flujo de aire limitado.',
 'Aunque tradicionalmente la mayoría de perros son buenos con los niños, todos los perros y niños necesitan que se les enseñe a llevarse bien y a respetarse mutuamente para estar seguros. Aun así, los perros y los niños pequeños nunca deberían quedarse solos y los adultos deben supervisar todas las interacciones entre ellos.'
 );"