psql example -c "INSERT INTO Razas_dogs(id, descripcion, consejos, personalidad,  origen, salud, ejercicio, nutricion, aseo, raza_nino)
 VALUES ('1',
 'Pese a su apariencia de terrier y su traviesa expresión similar a la de un mono, el Affenpinscher es un perro de compañía que en edad adulta mide entre 24 y 28 cm de la altura (contando desde las patas hasta la parte superior de la escápula) y pesa unos 3 o 4 kg. Su pelaje es áspero y suele ser negro aunque, a veces, también presenta un leve tono gris.',
 'Perro apto para dueños sin experiencia. Se requiere un adiestramiento básico. Le gustan los paseos activos. Le gusta pasear media hora al día. Perro pequeño. Babeo mínimo. Requiere aseo una vez por semana. Raza hipoalergénica. Perro expresivo y ladrador. No es un perro guardián. Puede necesitar entrenamiento para vivir con otras mascotas. Puede necesitar entrenamiento para vivir con niños',
 'El affen es alegre y seguro de sí mismo, irascible, tenaz y valiente, aunque muy cariñoso con sus dueños. Suele mostrarse receloso con los desconocidos; por lo que es esencial que se le socialice ya desde cachorro.',
 'El Affenpinscher, travieso y gracioso, es una de las razas más antiguas cuyo origen se remonta al siglo XVII. En Alemania, su lugar de origen, la palabra «affen» significa burlarse y «pinscher» equivale a terrier. El affen es el antepasado de otras dos razas, el grifón belga y el grifón de Bruselas, que también tienen una cara similar a la de un mono. Aunque los affen tienen las agallas de los terrier, son demasiado pequeños para ser perros de trabajo y se adquieren sobre todo como animales de compañía.',
 'La raza affenpinscher es una raza sana por lo general. Sin embargo, como ocurre con muchas razas pequeñas, puede padecer desplazamientos temporales de la rótula (luxaciones de rótula), problemas de cadera y de tráquea.',
 'A pesar de su tamaño reducido, es un perro activo y requiere de una cantidad razonable de ejercicio (de 20 a 40 minutos al día). Le gustan los juegos que le ayuden a ejercitar la mente, además del cuerpo, pero no son demasiado bulliciosos.', 
 'Los perros de tamaño miniatura tienen un metabolismo rápido, lo que significa que queman energía a un ritmo muy alto. Esto supone que, con un estómago tan pequeño, deben comer poco pero a menudo. Los alimentos para razas pequeñas están específicamente ideados con proporciones adecuadas de nutrientes clave y unos granos de pienso de menor tamaño que se adapten a bocas más pequeñas. Esto, además, estimula la masticación y mejora la digestión.',
 'El pelaje áspero y duro es lanudo en algunas partes y su aspecto natural es despeinado, por lo que no requiere grandes cuidados: un cepillado a la semana bastará.',
 'Aunque tradicionalmente la mayoría de perros son buenos con los niños, todos los perros y niños necesitan que se les enseñe a llevarse bien y a respetarse mutuamente para estar seguros. Aun así, los perros y los niños pequeños nunca deberían quedarse solos y los adultos deben supervisar todas las interacciones entre ellos.'
 );"