"""empty message

Revision ID: 5fb72657137d
Revises: 7e165eae3a2c
Create Date: 2022-11-05 03:21:09.029699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb72657137d'
down_revision = '7e165eae3a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answer1', sa.String(length=250), nullable=False))
    op.add_column('answer', sa.Column('answer2', sa.String(length=250), nullable=False))
    op.add_column('answer', sa.Column('answer3', sa.String(length=250), nullable=False))
    op.add_column('answer', sa.Column('answer4', sa.String(length=250), nullable=False))
    op.add_column('answer', sa.Column('answer5', sa.String(length=250), nullable=False))
    op.drop_constraint('answer_answer_key', 'answer', type_='unique')
    op.create_unique_constraint(None, 'answer', ['answer5'])
    op.create_unique_constraint(None, 'answer', ['answer2'])
    op.create_unique_constraint(None, 'answer', ['answer4'])
    op.create_unique_constraint(None, 'answer', ['answer1'])
    op.create_unique_constraint(None, 'answer', ['answer3'])
    op.drop_column('answer', 'answer')
    op.add_column('dogs', sa.Column('img_dog', sa.String(length=300), nullable=False))
    op.create_unique_constraint(None, 'dogs', ['img_dog'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dogs', type_='unique')
    op.drop_column('dogs', 'img_dog')
    op.add_column('answer', sa.Column('answer', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answer', type_='unique')
    op.drop_constraint(None, 'answer', type_='unique')
    op.drop_constraint(None, 'answer', type_='unique')
    op.drop_constraint(None, 'answer', type_='unique')
    op.drop_constraint(None, 'answer', type_='unique')
    op.create_unique_constraint('answer_answer_key', 'answer', ['answer'])
    op.drop_column('answer', 'answer5')
    op.drop_column('answer', 'answer4')
    op.drop_column('answer', 'answer3')
    op.drop_column('answer', 'answer2')
    op.drop_column('answer', 'answer1')
    # ### end Alembic commands ###
