"""empty message

Revision ID: 7e165eae3a2c
Revises: 
Create Date: 2022-11-04 03:59:46.972220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e165eae3a2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raza_dog', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raza_dog')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=250), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer')
    )
    op.create_table('razas_dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('consejos', sa.String(length=1000), nullable=False),
    sa.Column('personalidad', sa.String(length=1000), nullable=False),
    sa.Column('origen', sa.String(length=1000), nullable=False),
    sa.Column('salud', sa.String(length=1000), nullable=False),
    sa.Column('ejercicio', sa.String(length=1000), nullable=False),
    sa.Column('nutricion', sa.String(length=1000), nullable=False),
    sa.Column('aseo', sa.String(length=1000), nullable=False),
    sa.Column('raza_nino', sa.String(length=1000), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dog_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dogs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dogs_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_0', sa.String(length=50), nullable=False),
    sa.Column('result_1', sa.String(length=50), nullable=False),
    sa.Column('result_2', sa.String(length=50), nullable=False),
    sa.Column('result_3', sa.String(length=50), nullable=False),
    sa.Column('result_4', sa.String(length=50), nullable=False),
    sa.Column('result_5', sa.String(length=50), nullable=False),
    sa.Column('result_6', sa.String(length=50), nullable=False),
    sa.Column('result_7', sa.String(length=50), nullable=False),
    sa.Column('result_8', sa.String(length=50), nullable=False),
    sa.Column('result_9', sa.String(length=50), nullable=False),
    sa.Column('result_10', sa.String(length=50), nullable=False),
    sa.Column('result_11', sa.String(length=50), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_0'),
    sa.UniqueConstraint('result_1'),
    sa.UniqueConstraint('result_10'),
    sa.UniqueConstraint('result_11'),
    sa.UniqueConstraint('result_2'),
    sa.UniqueConstraint('result_3'),
    sa.UniqueConstraint('result_4'),
    sa.UniqueConstraint('result_5'),
    sa.UniqueConstraint('result_6'),
    sa.UniqueConstraint('result_7'),
    sa.UniqueConstraint('result_8'),
    sa.UniqueConstraint('result_9')
    )
    op.create_table('sabias_que',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiencia', sa.String(length=50), nullable=False),
    sa.Column('adiestramiento', sa.String(length=50), nullable=False),
    sa.Column('paseos', sa.String(length=50), nullable=False),
    sa.Column('tiempo_paseo', sa.String(length=50), nullable=False),
    sa.Column('tamano', sa.String(length=50), nullable=False),
    sa.Column('babeo', sa.String(length=50), nullable=False),
    sa.Column('aseo', sa.String(length=50), nullable=False),
    sa.Column('hipoalergenica', sa.String(length=50), nullable=False),
    sa.Column('ladrador', sa.String(length=50), nullable=False),
    sa.Column('guardian', sa.String(length=50), nullable=False),
    sa.Column('entre_otroPerros', sa.String(length=50), nullable=False),
    sa.Column('perro_familiar', sa.String(length=50), nullable=False),
    sa.Column('results_id', sa.Integer(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['results_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adiestramiento'),
    sa.UniqueConstraint('aseo'),
    sa.UniqueConstraint('babeo'),
    sa.UniqueConstraint('entre_otroPerros'),
    sa.UniqueConstraint('experiencia'),
    sa.UniqueConstraint('guardian'),
    sa.UniqueConstraint('hipoalergenica'),
    sa.UniqueConstraint('ladrador'),
    sa.UniqueConstraint('paseos'),
    sa.UniqueConstraint('perro_familiar'),
    sa.UniqueConstraint('tamano'),
    sa.UniqueConstraint('tiempo_paseo')
    )
    op.create_table('resp__sabias_que',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resp_boolean0', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean1', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean2', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean3', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean4', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean5', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean6', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean7', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean8', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean9', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean10', sa.Boolean(), nullable=False),
    sa.Column('resp_boolean11', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('sabiasque_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['sabiasque_id'], ['sabias_que.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resp__sabias_que')
    op.drop_table('sabias_que')
    op.drop_table('results')
    op.drop_table('user_dog_favorite')
    op.drop_table('razas_dogs')
    op.drop_table('answer')
    op.drop_table('user')
    op.drop_table('question')
    op.drop_table('dogs')
    # ### end Alembic commands ###
