"""empty message

Revision ID: bb02bc8ea808
Revises: 5fb72657137d
Create Date: 2022-11-15 01:55:10.227190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb02bc8ea808'
down_revision = '5fb72657137d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sabias_que', sa.Column('entre_otroperros', sa.String(length=50), nullable=False))
    op.drop_constraint('sabias_que_entre_otroPerros_key', 'sabias_que', type_='unique')
    op.create_unique_constraint(None, 'sabias_que', ['entre_otroperros'])
    op.drop_column('sabias_que', 'entre_otroPerros')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sabias_que', sa.Column('entre_otroPerros', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sabias_que', type_='unique')
    op.create_unique_constraint('sabias_que_entre_otroPerros_key', 'sabias_que', ['entre_otroPerros'])
    op.drop_column('sabias_que', 'entre_otroperros')
    # ### end Alembic commands ###
