"""empty message

Revision ID: e0b254045192
Revises: 5a0fad81e6c3
Create Date: 2022-11-13 16:24:24.308726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b254045192'
down_revision = '5a0fad81e6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sabias_que', 'experiencia',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'adiestramiento',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'paseos',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'tiempo_paseo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'tamano',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'babeo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'aseo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'hipoalergenica',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'ladrador',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'guardian',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'entre_otroPerros',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sabias_que', 'perro_familiar',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('sabias_que_adiestramiento_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_aseo_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_babeo_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_entre_otroPerros_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_experiencia_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_guardian_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_hipoalergenica_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_ladrador_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_paseos_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_perro_familiar_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_tamano_key', 'sabias_que', type_='unique')
    op.drop_constraint('sabias_que_tiempo_paseo_key', 'sabias_que', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sabias_que_tiempo_paseo_key', 'sabias_que', ['tiempo_paseo'])
    op.create_unique_constraint('sabias_que_tamano_key', 'sabias_que', ['tamano'])
    op.create_unique_constraint('sabias_que_perro_familiar_key', 'sabias_que', ['perro_familiar'])
    op.create_unique_constraint('sabias_que_paseos_key', 'sabias_que', ['paseos'])
    op.create_unique_constraint('sabias_que_ladrador_key', 'sabias_que', ['ladrador'])
    op.create_unique_constraint('sabias_que_hipoalergenica_key', 'sabias_que', ['hipoalergenica'])
    op.create_unique_constraint('sabias_que_guardian_key', 'sabias_que', ['guardian'])
    op.create_unique_constraint('sabias_que_experiencia_key', 'sabias_que', ['experiencia'])
    op.create_unique_constraint('sabias_que_entre_otroPerros_key', 'sabias_que', ['entre_otroPerros'])
    op.create_unique_constraint('sabias_que_babeo_key', 'sabias_que', ['babeo'])
    op.create_unique_constraint('sabias_que_aseo_key', 'sabias_que', ['aseo'])
    op.create_unique_constraint('sabias_que_adiestramiento_key', 'sabias_que', ['adiestramiento'])
    op.alter_column('sabias_que', 'perro_familiar',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'entre_otroPerros',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'guardian',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'ladrador',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'hipoalergenica',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'aseo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'babeo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'tamano',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'tiempo_paseo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'paseos',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'adiestramiento',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sabias_que', 'experiencia',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
