"""empty message

Revision ID: f4e0740ab46d
Revises: 5fb72657137d
Create Date: 2022-11-12 17:08:02.969395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e0740ab46d'
down_revision = '5fb72657137d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'answer1',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_constraint('answer_answer1_key', 'answer', type_='unique')
    op.drop_constraint('answer_answer2_key', 'answer', type_='unique')
    op.drop_constraint('answer_answer3_key', 'answer', type_='unique')
    op.drop_constraint('answer_answer4_key', 'answer', type_='unique')
    op.drop_constraint('answer_answer5_key', 'answer', type_='unique')
    op.drop_column('answer', 'answer3')
    op.drop_column('answer', 'answer5')
    op.drop_column('answer', 'answer4')
    op.drop_column('answer', 'answer2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answer2', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('answer4', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('answer5', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('answer3', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.create_unique_constraint('answer_answer5_key', 'answer', ['answer5'])
    op.create_unique_constraint('answer_answer4_key', 'answer', ['answer4'])
    op.create_unique_constraint('answer_answer3_key', 'answer', ['answer3'])
    op.create_unique_constraint('answer_answer2_key', 'answer', ['answer2'])
    op.create_unique_constraint('answer_answer1_key', 'answer', ['answer1'])
    op.alter_column('answer', 'answer1',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
